name: mess_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.6+1
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.8.4+4

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.jpg
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/splash.jpg
    - assets/logo.jpg
  uses-material-design: true
